name: Laravel CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          extensions: mbstring, pdo, mysql
          coverage: none

      - name: Copy .env
        run: cp .env.example .env

      - name: Install dependencies
        run: composer install --no-progress --prefer-dist

      - name: Run Code Style Check
        run: ./vendor/bin/pint --test  

      - name: Fix code style
        run: ./vendor/bin/pint
      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "style: fix code formatting" || echo "No changes"
          git push

      - name: Generate key
        run: php artisan key:generate

      - name: Setup SQLite DB
        run: |
          touch database/database.sqlite

      - name: Configure DB
        run: |
          sed -i 's/DB_CONNECTION=.*/DB_CONNECTION=sqlite/' .env
          sed -i 's/DB_DATABASE=.*/DB_DATABASE=database\/database.sqlite/' .env

      - name: Run migrations
        run: php artisan migrate

      - name: Set permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Run tests
        run: php artisan test